### ISSUE TITLE
CORS error

### ISSUE THREAD

**Issue by zadetek** [raymon-io/streamcompanion#1]
After recent update this great application doesn't load video anymore it looks like cors error, is it possible to fix ?

Regards

**Comment by raymon-io** [comment]
I haven't changed anything. It could be the fact that their server or cloudflare added more layers to block anything outside kick.com. Or maybe [corsproxy.io](https://github.com/raymon-io/streamcompanion/blob/be9dc36da7ba3ab1f55e092b66d1c65cfe50f3d6/src/app/kick/kickwatch/kickwatch.page.ts#L82) is not working. I will look into any alternative site or create my own cloud service. In the meantime you can look into the android , ios, windows apps if that helps.
https://github.com/raymon-io/streamcompanionCrossPlatform

**Comment by zadetek** [comment]
Thanks, android app still works will use that in the meantime.

**Comment by raymon-io** [comment]
Updated the website. You should be able to watch correctly now. It turns out the corsproxy url that I used do not work anymore. I had to use my own service. But you will have to clear cookie and data for streamcompanion.app if you are revisiting using the same browser. @zadetek

**Comment by zadetek** [comment]
Great thanks!
